name: New issue

on:
  issues:
    types: [opened]

jobs:
  issueCreated:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request && !startsWith(github.event.issue.title, 'Update stable version in repo') }}
    permissions:
      issues: write
    steps:
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: packages/iobroker.lametric
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for reporting!
            1. Please make sure your topic is not covered in the [documentation](https://github.com/klein0r/ioBroker.lametric/blob/master/docs/en/README.md)
            2. Ensure that you use the latest beta version (not the current stable version): **${{ steps.package-version.outputs.current-version}}**
            3. Please attach all necessary log files (in debug mode!), screenshots and other information to reproduce this issue
            ## Sponsored by
            [![ioBroker Master Kurs](https://haus-automatisierung.com/images/ads/ioBroker-Kurs.png)](https://haus-automatisierung.com/iobroker-kurs/?refid=github-actions)
